#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EllipticalWorkout.Resource", IsApplication=true)]

namespace EllipticalWorkout
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int workout_icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int bodyLayout = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int crossRamp = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int currentStage = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int fragmentView = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout2 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout3 = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int mainBackground = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int remainingView = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int resistance = 2131099661;
			
			// aapt resource value: 0x7f060014
			public const int startButton = 2131099668;
			
			// aapt resource value: 0x7f06000e
			public const int strides = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int textView1 = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int textView2 = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int textView3 = 2131099654;
			
			// aapt resource value: 0x7f060012
			public const int textView4 = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int timeRemainingInStage = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int totalElapsed = 2131099667;
			
			// aapt resource value: 0x7f060002
			public const int workoutBackground = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int workoutLevel = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int workoutName = 2131099653;
			
			// aapt resource value: 0x7f060015
			public const int workoutsView = 2131099669;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int monoandroidsplash = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int WorkoutFragmentView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int WorkoutListFragmentView = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int end_button = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int remoteUriBase = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int stage_template = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int start_button = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
